# Generated by Django 5.0 on 2024-01-18 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminuser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packages',
            name='Package_duration',
        ),
    ]
