# Generated by Django 5.0 on 2024-01-19 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminuser', '0002_remove_packages_package_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maritalstatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Religion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Religion_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cast', models.CharField(max_length=255)),
                ('Religion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminuser.religion')),
            ],
        ),
    ]
