# Generated by Django 5.0 on 2024-01-19 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminuser', '0003_maritalstatus_religion_cast'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usermember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Member_id', models.IntegerField()),
                ('Status', models.CharField(max_length=255)),
                ('Age', models.IntegerField()),
                ('Height', models.IntegerField()),
                ('Gender', models.CharField(max_length=30)),
                ('Place', models.CharField(max_length=255)),
                ('District', models.CharField(max_length=255)),
                ('Designation', models.CharField(max_length=255)),
                ('Contact', models.CharField(max_length=255)),
                ('Father_name', models.CharField(max_length=255)),
                ('Father_occupation', models.CharField(max_length=255)),
                ('Mother_name', models.CharField(max_length=255)),
                ('Mother_occupation', models.CharField(max_length=255)),
                ('Sibling_name', models.CharField(max_length=255)),
                ('Sibling_status', models.CharField(max_length=30)),
                ('Joining_date', models.DateField()),
                ('Image', models.ImageField(null=True, upload_to='image/')),
                ('cast', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminuser.cast')),
                ('religion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminuser.religion')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
