# Generated by Django 5.0 on 2024-01-19 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminuser', '0004_usermember'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermember',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
