# Generated by Django 5.0 on 2024-01-19 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminuser', '0005_usermember_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermember',
            name='Member_id',
            field=models.IntegerField(null=True),
        ),
    ]
