# Generated by Django 5.0 on 2024-01-19 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminuser', '0006_alter_usermember_member_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='usermember',
            name='Image',
        ),
        migrations.AddField(
            model_name='usermember',
            name='images',
            field=models.ManyToManyField(blank=True, to='adminuser.image'),
        ),
    ]
