# Generated by Django 5.0 on 2024-01-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminuser', '0008_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermember',
            name='package_expired',
            field=models.BooleanField(default=False),
        ),
    ]
