# Generated by Django 5.0 on 2024-01-22 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminuser', '0008_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.DateTimeField(auto_now_add=True)),
                ('Visited', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visited_set', to='adminuser.usermember')),
                ('Visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_set', to='adminuser.usermember')),
            ],
        ),
    ]
