# Generated by Django 5.0 on 2024-01-25 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminuser', '0009_usermember_package_expired'),
        ('user', '0003_message_is_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('is_request', models.BooleanField(default=False)),
                ('is_accept', models.BooleanField(default=False)),
                ('Receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_request', to='adminuser.usermember')),
                ('Sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_request', to='adminuser.usermember')),
            ],
        ),
    ]
