# Generated by Django 5.0 on 2024-01-25 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_message_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='message_request',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
